# Generated by Django 5.2.15 on 2026-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to='owners/aadhaar/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='business_doc',
            field=models.ImageField(blank=True, null=True, upload_to='owners/business_docs/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='digilocker_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='owners/selfies/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='verification_status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('pending_admin_review', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_verification', max_length=30),
        ),
    ]
