# Generated by Django 5.2.15 on 2026-08-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_emailotp_owner_aadhaar_card_owner_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='aadhaar_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='owners/aadhaar_back/'),
        ),
    ]
