# Generated by Django 5.2.15 on 2026-08-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_owner_aadhaar_card_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_business_doc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_selfie_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
