# Generated by Django 5.2.15 on 2026-09-19 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_firebase_uid_driver_is_phone_verified'),
        ('trips', '0004_trip_pickup_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_phone', models.CharField(max_length=20)),
                ('emergency_type', models.CharField(default='Medical Emergency', max_length=100)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('destination_address', models.TextField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('driver_assigned', 'Driver Assigned'), ('en_route', 'En Route'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to='drivers.driver')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
