# Generated by Django 5.2.15 on 2026-09-04 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('token_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PHONE_CONNECTED', 'Phone Connected'), ('AADHAAR_FRONT_REQUIRED', 'Aadhaar Front Required'), ('AADHAAR_FRONT_CAPTURED', 'Aadhaar Front Captured'), ('AADHAAR_BACK_REQUIRED', 'Aadhaar Back Required'), ('AADHAAR_BACK_CAPTURED', 'Aadhaar Back Captured'), ('AADHAAR_COMPLETED', 'Aadhaar Completed'), ('SELFIE_REQUIRED', 'Selfie Required'), ('SELFIE_CAPTURED', 'Selfie Captured'), ('REGISTRATION_COMPLETED', 'Registration Completed'), ('VERIFICATION_COMPLETED', 'Verification Completed'), ('SESSION_EXPIRED', 'Session Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=64)),
                ('phone_connected', models.BooleanField(default=False)),
                ('aadhaar_front', models.TextField(blank=True, null=True)),
                ('aadhaar_back', models.TextField(blank=True, null=True)),
                ('selfie', models.TextField(blank=True, null=True)),
                ('aadhaar_front_verified', models.BooleanField(default=False)),
                ('aadhaar_back_verified', models.BooleanField(default=False)),
                ('selfie_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_session',
                'ordering': ['-updated_at'],
            },
        ),
    ]
