# Generated by Django 5.2.15 on 2026-08-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0009_hospital_aadhaar_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('ambulance_type', models.CharField(choices=[('BLS', 'BLS'), ('ALS', 'ALS'), ('ICU', 'ICU'), ('Neonatal', 'Neonatal'), ('Patient Transport', 'Patient Transport')], max_length=30)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('busy', 'Busy'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='hospitals.hospital')),
            ],
            options={
                'verbose_name': 'Ambulance',
                'verbose_name_plural': 'Ambulances',
            },
        ),
    ]
