# Generated by Django 5.2.15 on 2026-08-24 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
        ('hospitals', '0009_hospital_aadhaar_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='hospital',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='hospitals.hospital'),
        ),
    ]
