# Generated by Django 5.2.15 on 2026-08-31 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_alter_ambulance_hospital'),
        ('hospitals', '0009_hospital_aadhaar_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='hospital',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='hospitals.hospital'),
        ),
    ]
