# Generated by Django 5.2.15 on 2026-08-31 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_alter_ambulance_hospital'),
        ('owners', '0004_owner_is_business_doc_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='owners.owner'),
        ),
    ]
