# Generated by Django 5.2.15 on 2026-09-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0004_ambulance_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='approval_status',
            field=models.CharField(choices=[('pending_admin_review', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_admin_review', max_length=30),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
