# Generated by Django 5.2.13 on 2026-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='accepted_by_id',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='accepted_by_type',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='assigned',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
