# Generated by Django 5.2.14 on 2026-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_remove_bloodrequest_accepted_by_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
