# Generated by Django 5.2.14 on 2026-06-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0003_bloodrequest_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='user_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
