# Generated by Django 5.2.15 on 2026-06-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0004_bloodrequest_user_address_bloodrequest_user_email_and_more'),
        ('hospitals', '0005_bloodinventory_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='hospitals.hospital'),
        ),
    ]
