# Generated by Django 5.2.15 on 2026-07-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0005_bloodrequest_accepted_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
