# Generated by Django 5.2.15 on 2026-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0006_bloodrequest_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='prescription',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='prescriptions/'),
        ),
    ]
