# Generated by Django 5.2.15 on 2026-07-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0007_alter_bloodrequest_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_component',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
