# Generated by Django 5.2.15 on 2026-09-19 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0008_bloodrequest_blood_component_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='prescription_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
