# Generated by Django 5.2.15 on 2026-08-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('aadhaar_card', models.ImageField(blank=True, null=True, upload_to='drivers/aadhaar/')),
                ('driving_licence', models.ImageField(blank=True, null=True, upload_to='drivers/licence/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='drivers/profile/')),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending_owner_review', 'Pending Owner Review'), ('approved_by_owner', 'Approved By Owner'), ('rejected_by_owner', 'Rejected By Owner'), ('pending_admin_review', 'Pending Admin Review'), ('approved_by_admin', 'Approved By Admin'), ('rejected_by_admin', 'Rejected By Admin')], default='pending_owner_review', max_length=30)),
                ('owner_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('aadhaar_ocr_data', models.JSONField(blank=True, null=True)),
                ('dl_ocr_data', models.JSONField(blank=True, null=True)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='ambulance.ambulance')),
            ],
        ),
    ]
