# Generated by Django 5.2.15 on 2026-09-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_complete_address_driver_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
