# Generated by Django 5.2.14 on 2026-06-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_remove_hospital_available_blood_hospital_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='blood_units',
            field=models.IntegerField(default=0),
        ),
    ]
