# Generated by Django 5.2.14 on 2026-06-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_bloodinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='hospitals.hospital'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bloodinventory',
            unique_together={('hospital', 'blood_group')},
        ),
    ]
