# Generated by Django 5.2.15 on 2026-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_bloodinventory_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
