# Generated by Django 5.2.15 on 2026-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_bloodinventory_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodinventory',
            name='fcm_token',
        ),
        migrations.AddField(
            model_name='hospital',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
