# Generated by Django 5.2.15 on 2026-06-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_remove_bloodinventory_fcm_token_hospital_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
