# Generated by Django 5.2.15 on 2026-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_hospital_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/aadhaar/'),
        ),
    ]
